### PR TITLE
added percentage calculation and display

### PR DESCRIPTION
**Pull request by RomainQueraud**
Hi @annatisch ,

I added a functionality to calculate the advancement of the rendering.

I count the number of tasks completed out of the number of tasks created.
For those which are in a running state, I analyze the logs and count the number of parts out of the total. This way, it is possible to measure the rendering advancement for videos or single images.

The file "helpers.py" is a file that I found on the azure tutorial : [https://azure.microsoft.com/en-us/documentation/articles/batch-python-tutorial/#step-6-monitor-tasks](https://azure.microsoft.com/en-us/documentation/articles/batch-python-tutorial/#step-6-monitor-tasks).
If modified it to fit my needs.

As it's my first contribution on Github, I hope it'll be fine. Tell me if anything needs to be changed.

Romain

### CODE REVIEW

**Comment by annatisch** [comment]
@RomainQueraud,
Thanks so much for this! I'll hopefully have a chance to review within the next few days.

**Comment by RomainQueraud** [comment]
Hi @annatisch,

I just added another commit. A button to the main menu that allows to manage the uploaded blobs without the need to go to the azure portal. You can view all files uploaded and delete them.
All new .py are named around "bfile" for Blender File. I based the structure on the pools.py files.

I also commented a few lines in the asset.py _assets() function :
 - commented 3 lines that led to a situation where the .blend was saved each time blender was started, preventing the green tickbox from showing in the asset menu.
 - removed the “if new_path != self.props.path” statement, because it prevented the asset tickbox refreshment. It led to situation like the following : asset is green ticked (uploaded) ==> we suppressed the blob in the blob menu ==> asset green tick was still there

**Comment by annatisch** [comment]
Hi @RomainQueraud,
Sorry this has taken me so long to get to - last week got crazy.
Changes look mostly good - though it seems there is an extra Blender.Client.zip - is this supposed to be there?
The only other issue is that the requirements for a bl id name (needed to register the class) are very restrictive, so using the blob name as the class ID isn't going to work in a large number of cases (loading this page fails for me due to this as some of my blobs have long names).
One way around this would be to attach some metadata to each asset that's uploaded with just a guid string, and use this as the class ID when listing them (although it would mean the page would only work for assets uploaded via the plugin).

Either way, I'm inclined to merge the changes as it's been my plan to restructure the job history page and pools page to be in a similar format to the assets page, and then I could make the same restructure to the blobs page as well (as I really like the feature) and the limitations would be removed for free.

So let me know about the zip file and then I'll be happy to merge :)

Thanks again for your efforts!

**Comment by RomainQueraud** [comment]
Hi @annatisch 

Thanks for taking the time to review it !

The zip is a mistake. I use to create it in order to test the whole thing in Blender and I didn’t paid attention that it was in the git commit. So it has nothing to do here.
I didn’t know about the restriction on the bl_idname length, that's why you changed the string name in the pools for example then.

However, I’m really pleased that you like the changes. I hope that it will be useful :-).

What I was thinking about was to have a way to monitor the state of the nodes created by the pool. Because, when the pool is in the steady state, the linked nodes can still be in the creating state and the job can’t be processed. Because it can take up to 30 minutes for a node to be ready (in my case), maybe it could be a good idea to have access to this information outside the azure portal ? 
I tried to look about it, but I wasn’t able to find a way to access the node’s state of a specific pool. I found this [msdn documentation](https://msdn.microsoft.com/en-us/library/azure/dn820159.aspx) but I didn’t managed to build the header for the request.

By the way, I also had to add a `-y` option to the `sudo apt-get install software-properties-common` line because it wasn’t working anymore on Monday. Maybe because one of the libraries updated ?

Really happy to take part of it :).

Cheers,
Romain

**Pull request merged**
